import os
from tornado.template import Template
import tornado.escape

def read_file(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def write_file(filepath, content):
    with open(filepath, 'w') as file:
        file.write(content)

def generate_html_from_template(template_path, output_path, context):
    template_content = read_file(template_path)
    template = Template(template_content, autoescape=None)  # Disable autoescaping
    rendered_content = tornado.escape.xhtml_unescape(template.generate(**context))
    write_file(output_path, rendered_content)

def generate_index(template_path, output_path, bingo_pages, page_images):
    template_content = read_file(template_path)
    template = Template(template_content, autoescape=None)
    rendered_content = tornado.escape.xhtml_unescape(
        template.generate(bingo_pages=bingo_pages, page_images=page_images)
    )
    write_file(output_path, rendered_content)

def main():
    template_filepath = 'bingo_template.html'
    contexts = {}

    contexts['christmas.html'] = {
        "title": "Christmas Bingo!",
        "background_image_url": "./holly.png",
        "color_scheme":  ['#ff0000', '#00a000', '#0000ff', '#ffbf00', '#9932CC'],
        "icon_emoji": "🎄",
        "marked_color": "#00a000",  # Or any color you want
        "board_emojis": "🎄🎅❄️⛄🎁",
        "tropes_list": [
                "City Slicker Finds Small-Town Love",
                "Attractive Widower or Devorcee",
                "Family Business Needs Saving",
                "Perfect Holiday Festival",
                "Workaholic Learns Holiday Spirit",
                "Small-Town Charm Wins Over Cynic",
                "Over-achiever Learns to Relax",
                "Small Town with Big Traditions",
                "Snowed-In!",
                "Sassy Friend Loves Holidays",
                "Snow Globe",
                
                "Grumpy Boss Finds Holiday Joy",
                
                "Miracle Saves the Holidays",
                "Special Ornament",
                "Big Family Gathering",
                "Adorable animal in a Santa Hat",
                "Romantic Carriage Ride in Town",
                "Epic Holiday Decor Showdown",
                
                "Snowfall at the Perfect Moment",
                "Mistletoe Kiss",
                "Holiday Schedule Chaos",
                "Big Secret Unveiled",
                
                "Hometown Hero Restores Spirit",
                "City Slicker Meets Rustic Charm",
                "Volunteer Event",
        
                "Clumsy Yet Sweet Helper",
                
                "Rivalry Over Decorations",
                "Magic Kiss on Christmas Eve",
                
                "Tree Lighting Ceremony",
                "Last-Minute Dash for Holiday Cheer",
                "Enemies Fall in Love at Christmas",
                "Town Legend of Christmas Magic",
                "Holiday Market",
                "Family Heirloom",
                "Assistant Finally Gets Their Moment",
                "Christmas Engagement",
                "Small-Town Love Interest",
                "City person can’t do small town things",
                "Secret Santa Gift with Meaning",
                "Plans Fall Apart",
                "Lost Pet Found",
                "Fake Dating Leads to Real Love",
                
                "Holiday Photoshoot",
                "Small-Town Festival",
                "Surprise Family Visit",
                "Holiday Costume Disaster",
                "Petty Argument Ends in Love",
                "Child Helps Adults Believe Again",
                "Snowball Fight",
                "Tree Farm",
                "Reindeer",
                "Hidden Talent",
                "Holiday Concert",
                "Holiday Grump",
                "Santa Stand-In",
                "Holiday Workaholic",
                "Over-bearing Relative",
                "Perfect Love Interest",
                "City Slicker",
                
                "Cynical Teen",
                "Grumpy Boss",
                "Elder shares wisdom",
                "Small Town with Big Christmas Spirit",
                "Family Cabin",
                "Busy Department Store",
                
                "Cozy Bakery",
                
                
                "Snowy Landscape",
                "Over-the-Top Holiday House",
                "Big City at Christmas",
                "'Save Christmas' Mission",
                "Mistaken Identity",
                "Holiday Bet or Dare",
                "Christmas Competition",
                "Return Home for the Holidays",
                "Christmas Wish",
                "Holiday Makeover",
                "Romantic Mix-Up",
                
                "Last-Minute Gift Dash",
                
                "Holiday Proposal",
                "Dcovery of True Meaning of Christmas",
                "Redemption and Forgiveness",
                "Overcoming Holiday Cynicism",
                "Conflict Across Generations",
                "Spirit of Giving",
                "Snowy Nights",
                "Mistletoe",
                "Caroling",
                
                "Ugly Christmas Sweaters",
                "Festive Food Feasts",
                "Christmas Markets",
                "Special Ornament",
                "Naughty or Nice",
                "Snow Globe",
                "Over-the-Top Neighbors",
                "Magical Creatures",
                "Stockings",
                "Christmas Lights",
                "Candy Canes",
                "Poinsettias",
                "Nativity Scenes",
                "Santa Claus",
                "Sitting with Santa",
                "Reindeer",
                "Sleighs",
                "Snowmen",
                
                "Gingerbread Houses",
                "Hot Cocoa or Eggnog",
                "Christmas Cookies",
                "Yule Log (Cake) or Fruit Cake",
                "Fire Roaring in the Fireplace",
                "Gift Wrapping Paper",
                "Christmas Morning",
                "Christmas Hits",
                "Holiday Movie Reference",
                "Christmas Villages",
                "Snowflakes",
                "Christmas Bells",
                "Santa Hats",
                "Winter Scarves",
                "Holiday Pajamas",
                "North Pole",
                "Christmas Elves",
                "Christmas Parties",
                "Gift Exchanges",
                "Caroling",
                
                "Snowball Fights",
                
                "Holiday Mugs",
                "Nutcracker",
                "French Horn in Soundtrack",
                "Sleigh Bells Ringing",
                "Christmas Stockings",
                "Festive Table Settings",
                "Holiday Baking",
                "Festive Wreaths",
                "Ice Skating",
                "Holiday Classics Music",
                "Holiday Magic",
                "Generous application of fake snow",
                "Generous application of hairspray",
            ],
        
    }

    contexts['halloween.html'] = {
        "title": "Halloween Bingo!",
        "background_image_url": "./spooky.png",
        "color_scheme":  ['#9A4DFF', '#FFB347',  '#9A4DFF', '#FFB347', '#9A4DFF'],
        "icon_emoji": "🎃",
        "marked_color": "#FFB347",  # Or any color you want
        "board_emojis": "🎃👻🍬🕷️🦇",
        "tropes_list": [
            "Jump Scare False Alarm",
            "Flashlight Batteries Die",
            "‘Let’s Split Up!’",
            "Mirror Scare",
            "Phone With No Signal",
            "Final Girl Energy",
            "Creepy Basement",
            "Chainsaw Guy",
            "Haunted Objects",
            "Eerie Lullabies",
            "Candy",
            "I'm Not Afraid!",
            "Stormy Night",
            "Car Won’t Start",
            "Running Upstairs Instead of Out",
            "Look Behind You",
            "Killer appears in Background",
            "The Killer Moves Really Slowly…",
            "Random Cat Jumping Out",
            "Stranger Knows Too Much",
            "‘It Was Just a Dream’",
            "Evil Laugh",
            "Possessed Child",
            "Old TV Static",
            "Locked From the Outside",
            "Flickering Lights",
            "The Call Is Coming From Inside the House",
            "Ancient Cursed Object",
            "Pumpkin Patch",
            "Local Legend",
            "Abrupt Weather Change",
            "Endless Fog Machine",
            "Fake-Out Death",
            "Evil Script",
            "Crowd Gasps in Unison",
            "Killer’s Mask Reveal",
            "Magic Book Nobody Should Open",
            "Make fun of Horror Clichés",
            "Blood on the Mirror",
            "Jump Cut to Screaming",
            "Safe then Not Safe",
            "Costumes",
            "Trick or Treating",
            "Haunted House Attraction",
            "Pumpkin Carving",
            "Spooky Decorations",
            "Full Moon",
            "Creepy Doll",
            "Monsters",
            "Killer is friend or family",
            "Killer is among us",
            "Killer theme music",
            "Good turned bad",
        ]

    }

    contexts['spooky.html'] = {
        "title": "Spooky Bingo!",
        "background_image_url": "./super_spooky.png",
        "color_scheme":  ["#43009B", "#C87500",  "#43009B", "#C87500", "#43009B"],
        "icon_emoji": "💀",
        "marked_color": "#C87500",  # Or any color you want
        "board_emojis": "🎃👻🍬🕷️🦇",
        "tropes_list": [
            "Demonic Possession",
            "Creepy Kid",
            "Haunted House",
            "Sleep Paralysis",
            "Family Secrets",
            "Witchcraft",
            "Cult Ritual",
            "Jump Scare",
            "Cursed Object",
            "Static TV",
            "Creepy Phone Call",
            "Bloody Bathroom",
            "Dream Killings",
            "Hallway of Blood",
            "Endless Maze",
            "Unstoppable Killer",
            "Chainsaw Chase",
            "Meat Hook",
            "Silent Stalker",
            "Hidden Caller",
            "Creepy Attic",
            "Occult Symbol",
            "Paranoid Neighbor",
            "Gaslighting",
            "Body Horror",
            "Cold Whisper",
            "Eyes Roll Back",
            "Possessed Voice",
            "Blood on the Walls",
            "Final Survivor"
        ]
    } 

    contexts['monster.html'] = {
    "title": "Monster Movies Bingo!",
    "background_image_url": "./monster.png",  # Add a monster-themed image to your project
    "color_scheme": ["#388e3c", "#212121", "#1976d2", "#fbc02d", "#b71c1c"],
    "icon_emoji": "👹",
    "marked_color": "#388e3c",
    "board_emojis": "👹🦖🦑🏙️⚡",
    "tropes_list": [
            "Monster Roar",
            "Heavy Footsteps",
            "Shadowy Silhouette",
            "Transformation Scene",
            "Monster Eye Close-Up",
            "Ancient Curse",
            "Creature Emerges from Water",
            "Fog Rolls In",
            "Monster Breaks Chains",
            "Screaming Crowd",
            "Monster Climbs Building",
            "Monster Attacks Village",
            "Monster Attacks City",
            "Army Arrives Too Late",
            "Military Fires Missiles",
            "Monster Shrugs Off Bullets",
            "Reporter Explains Danger",
            "Scientist With Chalkboard",
            "Monster Weakness Discovered",
            "Big Reveal Close-Up",
            "Monster vs Monster",
            "Creepy Lair",
            "Monster Bursts Through Wall",
            "Car Alarm Goes Off",
            "Claw Through Door",
            "Helicopter Crashes",
            "Crowd Gasps in Unison",
            "Monster Grabs Victim",
            "Hero Sacrifice",
            "Final Confrontation",
            "Monster Dies Dramatically",
            "Monster Disappears in Mist",
            "Eggs or Babies Discovered",
            "Sequel Tease",
            "Child Befriends Monster",
            "Villagers with Torches",
            "Monster Destroys Landmark",
            "Monster Theme Music",
            "Monster Roars Louder",
            "Stormy Night",
            "Blood Drip",
            "Monster Turns on Villain",
            "Victim Crawls Away",
            "Monster Shadow Looms",
            "Ancient Tomb Discovery",
            "Monster Awakens from Ice",
            "End Credits Roar",
            "Monster Smashes Helicopter",
            "City Skyline Pan",
            "Military Radio Chatter",
            "Monster Caught on Camera",
            "Monster Footprint Found",
            "Scientist Warns Everyone",
            "Nobody Listens",
            "Ancient Map",
            "Monster Shrugs Off Fire",
            "Monster Eats a Car",
            "Car Flipped Like a Toy",
            "Bridge Collapse",
            "Subway Scene",
            "Monster at Carnival",
            "Screams Drown Out Music",
            "Monster Attacks Boat",
            "Monster Destroys Plane",
            "Creature in the Sewer",
            "Monster Tail Smash",
            "Hero Uses Torch",
            "Monster Chained Up",
            "Chains Break Loudly",
            "Explosion Does Nothing",
            "Crowd Runs in Slow Motion",
            "Monster Climbs Mountain",
            "Monster Attacks Train",
            "Rain Pouring During Attack",
            "Electrical Wires Spark",
            "Monster Grabs Helicopter",
            "Soldiers Open Fire",
            "Radioactive Warning",
            "Monster Glowing Eyes",
            "Monster Knocked Down, Gets Up",
            "Creature Fossil Found",
            "Monster Statue in Temple",
            "Monster Worship Cult",
            "Monster Protects Child",
            "Villain Tries to Control Monster",
            "Monster Turns on Villain",
            "Monster Attacks Scientist",
            "Monster Burns in Sunlight",
            "Monster Retreats to Ocean",
            "Final Rocket Strike",
            "Monster Surrounded by Fire",
            "Dust Clears, Monster Gone",
            "Hero Says 'It’s Over' Too Soon",
            "Monster Bursts Back Alive",
            "Monster Roar Echoes",
            "Silhouette Against Moon",
            "Crowd Hides in Church",
            "Monster Crashes Through Window",
            "Creature Crawls on Ceiling",
            "Monster Grabs Airplane",
            "End Teaser"
        ]
    }
    
    contexts['slasher.html'] = {
        "title": "Slasher Films Bingo!",
        "background_image_url": "./slasher.png",  # Add a slasher-themed image to your project
        "color_scheme": ["#b71c1c", "#212121", "#757575", "#ffeb3b", "#263238"],
        "icon_emoji": "🔪",
        "marked_color": "#b71c1c",
        "board_emojis": "🔪😱🏕️🎭🌔",
        "tropes_list": [
            "Final Survivor",
            "Masked Killer",
            "Mask Reveal",
            "Iconic Mask",
            "Creepy Breathing",
            "Knife Glint",
            "Killer’s Gloved Hand",
            "Car Won’t Start",
            "Phone Line Cut",
            "Phone Call From Inside",
            "Group Splits Up",
            "Don’t Split Up",
            "First Victim Dies Early",
            "Killer’s POV Shot",
            "Weapon Close-Up",
            "Weapon From Kitchen",
            "Weapon Drops at Key Moment",
            "Killer Uses Unusual Weapon",
            "Creepy Old House",
            "Abandoned Cabin",
            "Abandoned Hospital",
            "Stormy Night",
            "Storm at Night",
            "Basement Scene",
            "Locked Door Panic",
            "Locked From Outside",
            "Lost Keys",
            "Hidden Body Discovered",
            "Victim Hides in Closet",
            "Victim Crawls Away",
            "Victim Trips While Running",
            "Victim Sacrifices Self",
            "Victim Calls for Help",
            "Running Upstairs Instead of Out",
            "Chase Through Woods",
            "Heavy Footsteps",
            "False Sense of Safety",
            "Killer’s Shadow Looms",
            "Killer Appears in Window",
            "Killer in the Backseat",
            "Killer in the Mirror",
            "Killer Melts into Shadows",
            "Unstoppable Killer",
            "Killer Back From Dead",
            "Killer Returns After Death",
            "Killer Disappears When Looked Away",
            "Killer’s Mask Removed",
            "Killer’s Catchphrase",
            "Killer’s Backstory Revealed",
            "Sequel Tease",
            "Final Showdown",
            "Final Confrontation in House",
            "Screaming Victim",
            "Scream Echo",
            "Jump Scare",
            "Jump Scare Cat",
            "Jump Cut to Screaming",
            "Fake-Out Death",
            "Fake Jump Scare",
            "Comic Relief Dies",
            "Teen Sneaks Off",
            "Sex Equals Death",
            "Pet Senses Danger",
            "Police Don’t Believe",
            "Police Arrive Too Late",
            "Friend Group Shrinks Fast",
            "Shower Scene",
            "Door Slams Shut",
            "Mirror Scare",
            "Bloody Weapon Drop",
            "Bloody Handprint",
            "Blood on the Walls",
            "Blood Dripping",
            "Blood Splatter on Camera",
            "Body Disappears",
            "Creepy Nursery Rhyme",
            "Creepy Lullaby",
            "Creepy Music Box",
            "Creepy Phone Ring",
            "Creepy Doll",
            "Creepy Mask Collection",
            "TV Static",
            "Empty Swing Moving",
            "Crowd Gasps in Unison",
            "Flashlight Flicker",
            "Broken Flashlight",
            "Power Goes Out",
            "Ambiguous Ending",
            "‘It Was Just a Prank’",
            "‘We Should Stay Together’",
            "‘Who’s There?’",
        ]
    }

    contexts['stranger_things.html'] = {
        "title": "Stranger Things Bingo!",
        "background_image_url": "./stranger.png",  # Add this image to your project
        "color_scheme": ['#d32f2f', '#212121', '#1976d2', '#fbc02d', '#388e3c'],
        "icon_emoji": "👾",
        "marked_color": "#d32f2f",
        "board_emojis": "🚲👦👧👨‍🔬👾",
        "tropes_list": [
            "Nosebleed Power",
            "Lights Flicker",
            "Demogorgon Attack",
            "Mind Flayer Shadow",
            "Vecna Curse",
            "Upside Down Portal",
            "Spore Fog",
            "Bike Chase",
            "Walkie-Talkie Call",
            "Dungeons & Dragons",
            "Eggo Waffles",
            "Government Van",
            "Hawkins Lab",
            "Russian Lab",
            "Secret Tunnel",
            "Underground Base",
            "Monster Screech",
            "Dragged Into Upside Down",
            "Music Saves the Day",
            "Running Through Woods",
            "Stormy Night",
            "Blood on Walls",
            "Dustin’s Hat",
            "Steve’s Perfect Hair",
            "Robin Sarcasm",
            "Erica Sass",
            "Nancy with a Gun",
            "Jonathan with Camera",
            "Hopper Punches Someone",
            "Hopper’s Hat",
            "Joyce with Axe",
            "Winona Yells ‘Will!’",
            "Max Headphones",
            "Billy Being Creepy",
            "Vecna Monologue",
            "Eleven Screams",
            "Papa Says ‘For Your Own Good’",
            "Mike Gives Speech",
            "Will Draws Map",
            "Surprise Betrayal",
            "Creepy Clock Chime",
            "Mirror Cracks",
            "Flashlight Dies",
            "Car Won’t Start",
            "Group Hug Finale",
            "’80s Song Drop",
            "Neon Lights",
            "Snowball Dance",
            "Scoops Ahoy Uniform",
            "Surfer Boy Pizza",
            "Rats Explode",
            "Body Horror Tentacles",
            "Shadow Monster Looms",
            "Kids Argue, Then Make Up",
            "Friend Gets Taken",
            "Final Battle in Gym",
            "Letters From Beyond",
            "Bloody Nose Pileup",
            "Portal Sealed (Again)",
            "Someone Says ‘Crazy’",
            "Steve Loses the Fight",
            "Dustin Explains Science Badly",
            "Mike Being Annoying",
            "Erica Roasts Everyone",
            "Joyce Goes Full Mom Mode",
            "Conspiracy Theory",
            "Someone Eats Too Many Eggos",
            "Hop’s Shirt Too Small",
            "Robin Rolls Her Eyes",
            "Monster Dies… Maybe?",
            "Plot Solved by Friendship",
            "Mike Dramatic Hand Hold",
            "Hopper Smokes Indoors",
            "Joyce With Christmas Lights",
            "Spooky Monster Noise",
            "Portal Opens",
            "Walkie-Talkie Static",
            "Favorite Snack Obsession",
            "Government Cover-Up",
            "Secret Lab",
            "Hidden Tunnel",
            "Creepy Woods",
            "Dragged Away Screaming",
            "Music Saves Someone",
            "Iconic Hair Moment",
            "Comic Relief Sidekick",
            "Sarcastic One-Liner",
            "Unexpected Guitar Solo",
            "Kid With Slingshot",
            "Sassy Comeback",
            "Teen With a Weapon",
            "Camera Flash Scene",
            "Parent Freak-Out",
            "Small Town Gossip",
            "Headphones Save the Day",
            "Creepy Villain Monologue",
            "Power Scream",
            "Authority Figure Punches Someone",
            "Hand-Drawn Map",
            "Betrayal Reveal",
            "Creepy Clock Sound",
            "Flashlight Flicker",
            "Car Trouble",
            "’80s Song Blast",
            "Mall or Fair Scene",
            "Uniform Joke",
            "Pizza Reference",
            "Gross Body Horror",
            "Shadow Monster Lurks",
            "Friends Argue",
            "Big Showdown",
            "Letters or Messages From Beyond",
            "Somebody Yells ‘Crazy!’",
            "Fan-Favorite Gets Hurt",
            "Conspiracy Theory Guy",
            "Mom Energy Moment",
            "Nat 20 Reference",
            ]
    }

    contexts['football.html'] = {
        "title": "Football Bingo!",
        "background_image_url": "./football.png",  # Add an NFL-themed image to your project
        "color_scheme": ["#024EA0", '#d50a0a', '#ffb612', '#008744', '#a5acaf'],
        "icon_emoji": "🏈",
        "marked_color": "#024EA0",
        "board_emojis": "🏈🎤🍔🎉📺",
        "tropes_list": [
                "Touchdown Dance",
                "QB Sack",
                "Interception",
                "Flag on the Play",
                "Field Goal Miss",
                "Pick Six",
                "Fumble Recovery",
                "Booth Review",
                "Timeout Called",
                "Announcer Says 'Momentum'",
                "Trick Play",
                "Challenge Flag",
                "Crowd Wave",
                "Timeout Ice the Kicker",
                "Injured Player Walks Off",
                "Mascot on Camera",
                "Coach Throws Headset",
                "Hail Mary Attempt",
                "Announcer Mentions College",
                "QB Sneak",
                "Announcer Says 'Clutch'",
                "Red Zone Drive",
                "Fourth Down Try",
                "Announcer Says 'Next Gen Stats'",
                "Wide Open Drop",
                "Bad Punt",
                "Announcer Mentions Fantasy Football",
                "Kicker Warming Up Alone",
                "Players Jawing After Whistle",
                "Announcer Mentions Weather",
                "Camera Cuts to Sad Fan",
                "Camera Cuts to Painted Fan",
                "Sideline Tablet Replay",
                "Announcer Says 'Separation'",
                "QB Hard Count",
                "Unneces. Roughness",
                "False Start",
                "Delay of Game",
                "Crowd Boos",
                "Announcer Says 'Any Given Sunday'",
                "QB Throws Helmet",
                "Coach Chewing Gum Aggressively",
                "Announcer Mentions Madden",
                "Camera on Crying Baby in Crowd",
                "Player Drinks Too Much Gatorade",
                "Mic’d Up Player Swears (Muted)",
                "Announcer Says 'He Wants That One Back'",
                "Camera Cuts to Celebrity Fan",
                "QB Blames Receiver",
                "Ref Explains Call for Too Long",
                "Announcer Says 'Trickery'",
                "Theme Music Plays Too Loud",
                "Cut to Halftime Show Rehearsal",
                "Crowd Dances on Camera",
                "Overly Dramatic Slow-Mo Replay",
                "Theme Song from SNF/MNF",
                "Announcer Says 'That’s Why You Play the Game'",
                "Fans Wearing Costumes",
                "Hot Dog Eating in Stands",
                "Camera Zooms on Angry Coach",
                "Fan With Funny Sign",
                "Announcer Says 'Razzle Dazzle'",
                "Awkward Post-Play Celebration",
                "Theme Music Stinger After Ad Break",
                "Ref Forgetting to Turn Off Mic",
                "Slow Clap",
                "Mascot Trips",
                "Theme Music Mash-Up Montage",
                "Announcer Messes Up Name",
                "Ball Bounces Off Helmet",
                "Fan Falls on Camera",
                "Replay Sponsored by Random Product",
                "Pass Interference",
                "Holding",
                "Offside",
                "Personal Foul",
                "Unsports. Conduct",
                "Roughing the Passer",
                "Illegal Formation",
                "Illegal Motion",
        ]
    }

    contexts['romcom.html'] = {
        "title": "Rom-Com Bingo!",
        "background_image_url": "./romcom.png",  # Add a rom-com-themed image to your project
        "color_scheme": ["#e91e63", "#ffeb3b", "#2196f3", "#4caf50", "#ff9800"],
        "icon_emoji": "❤️",
        "marked_color": "#e91e63",
        "board_emojis": "❤️💌🌹🍷🎶",
        "tropes_list": [
            "Meet-Cute",
            "Accidental Kiss",
            "Love Triangle",
            "Grand Romantic Gesture",
            "Best Friend Confidant",
            "Misunderstanding",
            "Makeover Montage",
            "Chasing After Love Interest",
            "Running Through Airport",
            "Rain Kiss",
            "Wedding Crash",
            "Fake Relationship",
            "Opposites Attract",
            "Secret Admirer",
            "Love Letter",
            "Unexpected Confession",
            "Song Dedication",
            "Dancing Together",
            "Cooking Together",
            "Accidental Text Message",
            "Jealousy Scene",
            "Reunion Scene",
            "Heartfelt Apology",
            "Surprise Date",
            "Couple’s First Fight",
            "Cute Pet Interaction",
            "Holiday Romance",
            "Bookstore Encounter",
            "Coffee Shop Meeting",
            "Art Gallery Scene",
            "Music Festival Date",
            "Road Trip Together",
            "Picnic in the Park",
            "Stargazing Scene",
            "Couple’s Inside Joke",
            "Shared Secret Moment",
            "Late-Night Phone Call",
            "Dramatic Rain Scene",
            "Unexpected Dance-Off",
            "Couple’s First Home Cooked Meal",
            "Surprise Visit from Out of Town",
            "Meet Parents Disaster",
            "Montage with Pop Song",
            "Love Confession Interrupted",
            "Public Declaration of Love",
            "Slow Motion Eye Contact",
            "Overheard Conversation",
            "Grandma Knows Everything",
            "Fake Relationship Becomes Real",
            "‘It’s Not What It Looks Like!’",
            "Proposal Gone Wrong",
            "Funny Text Exchange",
            "Romantic Flashback",
            "‘We’re Just Friends’ (They’re Not)",
            "Clumsy Fall into Arms",
            "Heartfelt Speech",
            "Cooking Disaster",
            "They Reconnect at a Wedding",
            "Romantic Song Plays at Perfect Time",
            "Workplace Romance Reveal",
            "‘You Complete Me’ Moment",
            "Kiss Interrupted by Phone Call",
            "Sudden Downpour",
            "Rival Turns Out to Be Nice",
            "Someone Runs Through an Airport",
            "Flower Shop Scene",
            "Embarrassing Karaoke",
            "Romantic Montage in City Streets",
            "Accidental Confession",
            "Cute Nickname Revealed",
            "Group of Friends Cheer On",
            "Unexpected Wedding Invitation",
            "Hug That Lasts Too Long",
            "Closing Scene Kiss"
            ]
    }

    contexts['western.html'] = {
        "title": "Western Bingo!",
        "background_image_url": "./western.png",  # Add a western-themed image to your project
        "color_scheme": ["#6D4C41", "#FFEB3B", "#1976D2", "#388E3C", "#D32F2F"],
        "icon_emoji": "🤠",
        "marked_color": "#6D4C41",
        "board_emojis": "🤠🐎🌵🔫🏜️",
        "tropes_list": [
            "Showdown at High Noon",
            "Dusty Desert Town",
            "Saloon Brawl",
            "Wanted Poster",
            "Sheriff’s Badge",
            "Horseback Chase",
            "Train Robbery",
            "Cactus Close-Up",
            "Whiskey Shot",
            "Gunfight in the Street",
            "Stagecoach Ride",
            "Lassoing Scene",
            "Campfire Storytelling",
            "Tumbleweed Rolling By",
            "Outlaw Gang",
            "Duel at Dawn",
            "Rustler Attack",
            "Bank Heist",
            "Posse Formation",
            "Desert Sunset",
            "Spur Jingle",
            "Cattle Drive",
            "Saloon Piano Music",
            "Sheriff vs Outlaw Standoff",
            "Gold Rush Discovery",
            "Barroom Dance",
            "Train Station Arrival",
            "Wagon Wheel Close-Up",
            "Desert Storm",
            "Ranch Hand Work",
            "Homestead Scene",
            "Frontier Justice",
            "Bounty Hunter Arrival",
            "Gun Holster Close-Up",
            "Desert Oasis",
            "Sheriff’s Office Scene",
            "Outlaw Hideout",
            "Horse Taming Scene",
            "Desert Night Sky",
            "Saloon Showdown",
            "Wanted Dead or Alive Sign",
            "Cattle Rustling Scene",
            "Train Tracks Close-Up",
            "Desert Canyon Chase",
            "Sheriff’s Posse Ride Out",
            "Outlaw Capture Scene",
            "Gunfight Finale",
            "Poker Game Tension",
            "Mysterious Stranger Arrives",
            "Cigar Chomp Before Duel",
            "Slow Pan to Revolver",
            "Boots Crunch on Gravel",
            "Hero Rides into Sunset",
            "Villain Twirls Mustache",
            "Bartender Wipes Glass",
            "Hat Blows Away in Wind",
            "Horse Neigh Echoes",
            "Betrayal for Gold",
            "Long Walk into Town",
            "Saloon Doors Swinging",
            "Rattlesnake Rattle",
            "Crossed Pistols Shadow",
            "Dust Devil Spins",
            "Shot Glass Shatters",
            "Train Whistle at Dawn",
            "Desert Vultures Circling",
            "Old Prospector Rambling",
            "Rancher’s Daughter Scene",
            "Saddle Up Montage",
            "Silent Stranger Saves the Day",
            "Guitar Strum by Campfire",
            "Shootout in the Rain",
            "Old Wanted Poster Flutters",
            "Outlaw Gets Away (For Now)",
            "Horses Gallop into Horizon",
            "Rifle Reload Close-Up",
            "Deputy Earns His Star",
            "Hat Tip Goodbye"
        ]
    }

    contexts['action.html'] = {
        "title": "Action Movie Bingo!",
        "background_image_url": "./action.png",  # Add an action-themed image to your project
        "color_scheme": ["#D32F2F", "#1976D2", "#388E3C", "#FBC02D", "#212121"],
        "icon_emoji": "💥",
        "marked_color": "#D32F2F",
        "board_emojis": "💥🚗🔫🕶️🏃",
        "tropes_list": [
                "Car Chase",
                "Explosion",
                "Hero Walks Away from Explosion",
                "Gunfight",
                "Martial Arts Fight",
                "Helicopter Scene",
                "Villain Monologue",
                "Last-Minute Save",
                "High-Speed Pursuit",
                "Undercover Operation",
                "Gadget Reveal",
                "Hostage Rescue",
                "Car Flip",
                "Bullet Time Scene",
                "Train Heist",
                "Final Showdown",
                "Sniper Shot",
                "Hacking Scene",
                "Plane Hijack",
                "Boat Chase",
                "Rooftop Jump",
                "Disguised Identity",
                "Explosive Device Defusal",
                "Car Explosion Close-Up",
                "Hero Gets Back Up After Being Shot",
                "Villain Escapes Again",
                "Secret Lair Reveal",
                "Hero Uses Improvised Weapon",
                "Daring Infiltration",
                "Epic One-Liner Before Fight",
                "Chase Through Crowded Market",
                "Underwater Escape",
                "Car Jumps Ramp",
                "Helicopter Crash",
                "Villain’s Henchman Betrayal",
                "High-Tech Surveillance Hack",
                "Explosive Car Door Kick-In",
                "Hero Saves Civilians Amid Chaos",
                "Final Duel on Moving Vehicle",
                "Slow Motion Explosion",
                "Hero Dangling From Cliff",
                "Motorcycle Chase",
                "Knife Fight",
                "Falling Off a Skyscraper",
                "Fight Scene in Kitchen",
                "Secret Government Agency",
                "Villain Says ‘You’re Too Late!’",
                "Hand-to-Hand Combat in Rain",
                "Someone Says ‘Go! I’ll Hold Them Off!’",
                "Hero Escapes Just in Time",
                "Double Agent Reveal",
                "Laser Security System",
                "Disguised Entry Into Base",
                "Tracking Device Found",
                "Villain Has a Scar",
                "Hero Bleeding but Keeps Fighting",
                "Car Crashes Through Glass",
                "Helicopter Rescue",
                "Chase Through Subway",
                "Weapon Hidden in Everyday Object",
                "Fight on a Moving Train",
                "Explosion Underwater",
                "Slow Clap by Villain",
                "Hero Outruns Fireball",
                "Briefcase Full of Money",
                "Mission Briefing Scene",
                "Map with Red Lines",
                "Countdown Timer on Bomb",
                "Team Montage Before Mission",
                "Helicopter Shot of City",
                "Villain’s Evil Laugh",
                "Hero Refuses the Mission",
                "Betrayal Twist",
                "Main Character Thought Dead Returns",
                "Secret Escape Tunnel",
                "Villain’s Base Blows Up",
                "Hero and Villain Team Up Temporarily",
                "Innocent Civilian Helps Save the Day",
                "Falling Debris Narrowly Misses Hero",
                "Ending Helicopter Shot",
                "Freeze Frame Victory Pose"
            ]
    }

    for filename, context in contexts.items():
        context['page_name'] = filename
        context['other_pages'] = [f for f in contexts.keys() if f != filename]
        generate_html_from_template(template_filepath, filename, context)

    # After generating bingo pages
    index_template_path = 'index_template.html'
    index_output_path = 'index.html'
    bingo_pages = list(contexts.keys())

    # Dynamically generate page_images from contexts
    page_images = {filename: context['background_image_url'] for filename, context in contexts.items()}

    generate_index(index_template_path, index_output_path, bingo_pages, page_images)

if __name__ == "__main__":
    main()
